### ISSUE TITLE
Blank settings

### ISSUE THREAD

**Issue by kmaustral** [jgchristopher/obsidian-clipper#61]
I just updated to the Beta version 1.0.0 - beta 1. When I go to the settings, the screen is blank. I tried re-starting, but it was the same.

**Comment by jgchristopher** [comment]
Would you mind providing a screenshot?

Also, did you have the previous version of the plugin installed before?

Any chance that you could do the following steps? This would help me a ton.

1. Open Settings in Obsidian and go to the `Community Plugin` settings
2. Turn off the Obsidian-Clipper plugin
3. In the menu of Obsidian, click View -> Toggle Developer Tools
4. Click on the `Console` tab of the developer tools that showed up
5. Copy any error output in the console to this ticket

Thanks!

**Comment by kmaustral** [comment]
Thanks for your message, John.

I did have a previous version installed.

This is the error message:

plugin:obsidian-clipper:15160 Uncaught (in promise) TypeError: Cannot read
properties of undefined (reading 'length')
    at create_fragment12 (plugin:obsidian-clipper:15160:34)
    at init (plugin:obsidian-clipper:9432:37)
    at new SettingsComponent (plugin:obsidian-clipper:15331:5)
    at SettingTab.display (plugin:obsidian-clipper:16079:17)
    at SettingsSearch.getTabResources (plugin:settings-search:229:15)
    at t.eval (plugin:settings-search:267:18)
    at t.wrapper [as addSettingTab] (plugin:settings-search:59:20)
    at t.addSettingTab (app.js:1:2020191)
    at ObsidianClipperPlugin.onload (plugin:obsidian-clipper:15931:10)

Let me know if you have any more questions.

Thanks for plugin.

**Comment by kmaustral** [comment]
And FYI, I did now uninstall the plugin and delete the folder. When I
reinstalled it, the settings appeared.

**Comment by kmaustral** [comment]
There is one issue I recall from before which is recurring. Whichever
heading I put into the settings (level 1 heading), it is not able to find:

Uncaught (in promise) Error: Missing Expected Heading
    at AppendWriter.write (plugin:obsidian-clipper:4762:15)
write @ plugin:obsidian-clipper:4762
await in write (async)
handleWrite @ plugin:obsidian-clipper:4900
writeToPeriodicNote @ plugin:obsidian-clipper:4920
await in writeToPeriodicNote (async)
eval @ plugin:obsidian-clipper:10885
t @ app.js:1
(anonymous) @ VM353:1
(anonymous) @ node:electron/js2c/renderer_init:2
(anonymous) @ node:electron/js2c/renderer_init:2
emit @ node:events:513
onMessage @ node:electron/js2c/renderer_init:2

For the time being, I'm not using a Heading and just appending it to the
Daily Note.

**Comment by kmaustral** [comment]
Latest update. I updated to the new Beta version 1 and lost the settings
again.

**Comment by yarub123** [comment]
Yeah I'm getting a similar issue. Blank settings and it's also not clipping anymore.  I don't know if it has to do with Obsidians new policy and maybe the required name change for manifest?

Here are **3 outputs**:
- (1) VM209 plugin:obsidian-clipper:15923 
- Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$destroy')
    at BookmarkletLinksView.onClose (VM209 plugin:obsidian-clipper:15923:15)
    at BookmarkletLinksView.<anonymous> (app.js:1:1402935)
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at app.js:1:236279
    at new Promise (<anonymous>)
    at v (app.js:1:236024)
    at t.close (app.js:1:1402796)
    at t.<anonymous> (app.js:1:1825679)
    at app.js:1:237258

- (2) plugin:obsidian-clipper:15160 
- Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at create_fragment12 (plugin:obsidian-clipper:15160:34)
    at init (plugin:obsidian-clipper:9432:37)
    at new SettingsComponent (plugin:obsidian-clipper:15331:5)
    at SettingTab.display (plugin:obsidian-clipper:16079:17)
    at t.openTab (app.js:1:2741344)
    at t.openTabById (app.js:1:2741926)
    at Handlers.handleOpenSettings (plugin:obsidian-advanced-uri:4007:19)
    at AdvancedURI.chooseHandler (plugin:obsidian-advanced-uri:4616:21)
    at eval (plugin:obsidian-advanced-uri:4541:12)
    at t (app.js:1:2015614)

This 3rd error is what happens **when I try to clip** something:
- (3) plugin:obsidian-clipper:15987 
- Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'find')
    at eval (plugin:obsidian-clipper:15987:54)
    at t (app.js:1:2015614)
    at <anonymous>:1:52
    at node:electron/js2c/renderer_init:2:17004
    at EventEmitter.<anonymous> (node:electron/js2c/renderer_init:2:11193)
    at EventEmitter.emit (node:events:513:28)
    at Object.onMessage (node:electron/js2c/renderer_init:2:9266)

**Comment by jgchristopher** [comment]
I am working on migrating settings for existing users.

**Comment by yarub123** [comment]
Appreciate ya Chris. Take your time. Thanks for keeping us updated ❤️
